### ISSUE TITLE
Missing equals/hashcode on AccountDetailsImpl?

### ISSUE THREAD

**Issue by mbucc** [Nick-Triller/accounting#8]
Should the following test pass?

```
    @Test
    void testSetEquality() {

        Set<AccountDetails> xs = new HashSet<>();

        xs.add(new AccountDetailsImpl("1", "one", DEBIT));
        xs.add(new AccountDetailsImpl("1", "one", DEBIT));

        assertEquals(1, xs.size());
    }
```

If so, you could annotate AccountDetailsImpl with  `@EqualsAndHashCode`, and then it will pass.

It does raise an interesting question though, what is equality for an AccountDetail?

I'm hacking on a TSV reader and used equals in my test, so for simplicity convenience I used the three-field equals instead of just the account number.  Though I think it would be better to fail if someone loads two accounts with the same account number and different names.

**Comment by Nick-Triller** [comment]
Hi,

I think the test should pass. Feel free to add `@EqualsAndHashCode` if it simplifies your code. I didn't add it simply because there was no need for it.

I agree there should be no two accounts with the same account number and different names. When an `AccountDetails` object is added to a ledger, an exception will be thrown if the account number is already in use:
```java
    private void addAccount(AccountDetails accountDetails) {
        String newAccountNumber = accountDetails.getAccountNumber();
        boolean accountNumberNotInUse = !accountNumberToAccount.containsKey(newAccountNumber);
        checkArgument(accountNumberNotInUse,
                "An account with the account number %s exists already in the ledger", newAccountNumber);
        accountNumberToAccount.put(accountDetails.getAccountNumber(), new Account(accountDetails));
    }
```
Best
Nick
